
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multicam-tracker-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=multicam_tracker
      - DEBUG=true
    networks:
      - multicam-network

  mongodb:
    image: mongo:5.0
    container_name: multicam-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=multicam_tracker
    networks:
      - multicam-network

networks:
  multicam-network:
    driver: bridge

volumes:
  mongodb_data:
